### ISSUE TITLE
screen recorder 개발

### ISSUE THREAD

**Issue by pjhxp** [sorrowhill/FFmpegTutorial#1]
안녕하세요. 
FFMPEG로 동영상 저장하는 기능 개발중에 이기곤님의 책의 도움 많이 받았습니다.
마지막 예제도 좋은데, 제가 개발하는 기능은 
1) 현재 화면을 bitmap으로 저장하고
2) 이를 avcodec_encode_video2 함수를 사용하여 encoding하는 비교적 간단한 작업니다.

문제는 단 10초를 녹화하더라도, **뒤로 갈 수록 영상품질이 나빠져서** 나중에는 알아볼 수 없게 되는 것입니다.
video codec으로 AV_CODEC_ID_H264 사용하고 있으며 각종 옵션을 조정해 봤는데, 도저히 방법을 모르겠습니다.
개인적으로 연락 드리는 방법을 몰라, 이슈로 올려봅니다.
꼭 조언 좀 부탁드립니다.
제 이메일 주소는 pjh_xp@naver.com 입니다.

**Comment by ggkollective** [comment]
메일로 답장 드렸습니다. 연락이 늦어 죄송합니다.
